# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://isuzu-mobil.github.io
title: Dealer Isuzu Resmi
email: faridzisuzu@gmail.com
author: Faridz Fikri
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2019 isuzu-mobil.github.io. All Rights Reserved.'
credits: # 'Credits: Open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: 
  - title: github
    url: 
  - title: whatsapp
    url: 
